name: Confluent Schema Registry Automation

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  CLUSTER: psrc-4r3n1.us-central1.gcp.confluent.cloud
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET: ${{ secrets.API_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt install -y curl
          curl --version

      - name: Register New Schema
        run: |
          # Use curl or other tools to make HTTP requests to register new schema in Schema Registry API
          # Example: curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" --data '{"schema": "..."}' http://schema-registry:8081/subjects/your-topic-value/versions
          # Use appropriate authentication and error handling
          curl -u ${{ env.API_KEY }}:${{ env.API_SECRET }} \
            -X POST https://${{ env.CLUSTER }}/subjects/device-subscription-value/versions \
            -H "Content-Type:application/json" \
            -d @file.json DeviceSubscription/DeviceSubscription.json
          
