name: Confluent Schema Registry Automation

on:
  push:
    branches:
      - main

env:
  CLUSTER: http://schema-registry:8081
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET: ${{ secrets.API_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          get -qO - https://packages.confluent.io/confluent-cli/deb/archive.key | sudo apt-key add
          sudo apt install software-properties-common
          sudo add-apt-repository "deb https://packages.confluent.io/confluent-cli/deb stable main"
          sudo apt update
          sudo apt install confluent-cli
