name: Confluent Schema Registry Automation

on:
  push:
    branches:
      - main
      - 'feature/**'

env:
  CLUSTER: http://schema-registry:8081
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET: ${{ secrets.API_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          wget -qO - https://packages.confluent.io/confluent-cli/deb/archive.key | sudo apt-key add
          sudo apt install software-properties-common
          sudo add-apt-repository "deb https://packages.confluent.io/confluent-cli/deb stable main"
          sudo apt update
          sudo apt install confluent-cli
          confluent --version
          
      - name: Register New Schema
        run: |
          # Use curl or other tools to make HTTP requests to register new schema in Schema Registry API
          # Example: curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" --data '{"schema": "..."}' http://schema-registry:8081/subjects/your-topic-value/versions
          # Use appropriate authentication and error handling
          confluent schema-registry schema create \
           -- subject device-subscription-value \
           -- schema DeviceSubscription/DeviceSubscription.json
           -- type json
           -- api-key ${{ env.API_KEY }}
           -- api-secret $ {{ env.API_SECRET }}
      
